name: Deploy multiple previews on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build preview bundle
        env:
          MAGIC_BAR_BASE_URL: ${{ secrets.MAGIC_BAR_BASE_URL || 'https://mementum-test-preview.web.app' }}
        run: npm run build:prod

      # Deploy to consistent preview URL
      - name: Deploy to fixed preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEMENTUM_TEST }}
          projectId: mementum-test
          channelId: test-preview # Consistent URL

      # Deploy to unique preview URL per PR
      - name: Deploy to unique PR preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEMENTUM_TEST }}
          projectId: mementum-test
          channelId: pr-${{ github.event.number }} # Unique URL per PR
